import { defineConfig } from 'tsup';

export default defineConfig({
    entry: {
        index: 'src/index.ts',
        lite: 'src/lite.ts',
        core: 'src/core/index.ts',
        memory: 'src/memory/index.ts',
        providers: 'src/providers/index.ts',
        tools: 'src/tools/index.ts',
        planner: 'src/planner/index.ts',
        execution: 'src/execution/index.ts',
        orchestration: 'src/orchestration/index.ts',
        observability: 'src/observability/index.ts',
        agentic: 'src/agentic/index.ts',
        'adapter-redis': 'src/adapter-redis/index.ts',
        session: 'src/session/index.ts',
        guardrails: 'src/guardrails/index.ts',
        knowledge: 'src/knowledge/index.ts',
        storage: 'src/storage/index.ts',
        db: 'src/db/index.ts',
        production: 'src/production/index.ts',
        artifacts: 'src/artifacts/index.ts',
        compression: 'src/compression/index.ts',
        context: 'src/context/index.ts',
        eval: 'src/eval/index.ts',
        voice: 'src/voice/index.ts',
        runtime: 'src/runtime/index.ts',
        shared: 'src/shared/index.ts',
        skills: 'src/skills/index.ts',
        models: 'src/models/index.ts',
        router: 'src/router/index.ts',
        reasoning: 'src/reasoning/index.ts',
        scheduler: 'src/scheduler/index.ts',
        model: 'src/model.ts',
        tool: 'src/tool.ts',
        workflow: 'src/workflow.ts',
        guard: 'src/guard.ts',
        serve: 'src/serve.ts',
        observe: 'src/observe.ts',
        test: 'src/test.ts',
        /** Subpath `confused-ai/create-agent` — lean entry without pulling the full umbrella bundle */
        'create-agent': 'src/create-agent.ts',
        cli: 'src/cli/index.ts',
        /** Shell tools — separate entry to avoid accidental exposure */
        'tools/shell': 'src/tools/utils/shell-entry.ts',
        /** Tool category subpath entries */
        'tools/core': 'src/tools/core/index.ts',
        'tools/mcp': 'src/tools/mcp/index.ts',
        'tools/utils': 'src/tools/utils/index.ts',
        'tools/communication': 'src/tools/communication/index.ts',
        'tools/productivity': 'src/tools/productivity/index.ts',
        'tools/devtools': 'src/tools/devtools/index.ts',
        'tools/crm': 'src/tools/crm/index.ts',
        'tools/search': 'src/tools/search/index.ts',
        'tools/scraping': 'src/tools/scraping/index.ts',
        'tools/media': 'src/tools/media/index.ts',
        'tools/memory': 'src/tools/memory/index.ts',
        'tools/ai': 'src/tools/ai/index.ts',
        'tools/data': 'src/tools/data/index.ts',
        'tools/finance': 'src/tools/finance/index.ts',
        'tools/social': 'src/tools/social/index.ts',
        contracts: 'src/contracts/index.ts',
        interfaces: 'src/interfaces.ts',
        plugins: 'src/plugins/index.ts',
        adapters: 'src/adapters/index.ts',
        background: 'src/background/index.ts',
        testing: 'src/testing/index.ts',
        'test-utils': 'src/test-utils/index.ts',
        'test-utils/conformance': 'src/test-utils/conformance.ts',
        learning: 'src/learning/index.ts',
        video: 'src/video/index.ts',
        config: 'src/config/index.ts',
        dx: 'src/dx/index.ts',
        sdk: 'src/sdk/index.ts',
        graph: 'src/graph/index.ts',
        simulation: 'src/simulation/index.ts',
        playground: 'src/playground.ts',
    },
    format: ['cjs', 'esm'],
    dts: false,
    splitting: false,
    sourcemap: false,
    clean: true,
    treeshake: true,
    /** Lazy `require()` — install only what you use; must not be resolved at bundle time */
    external: [
        '@anthropic-ai/sdk',
        '@aws-sdk/client-dynamodb',
        '@google/generative-ai',
        '@ffmpeg-installer/ffmpeg',
        '@libsql/client',
        '@opentelemetry/exporter-prometheus',
        '@sendgrid/mail',
        'better-sqlite3',
        'chromadb',
        'fluent-ffmpeg',
        'ioredis',
        'mongodb',
        'mysql2',
        'mysql2/promise',
        'neo4j-driver',
        'nodemailer',
        'openai',
        'pdf-parse',
        'pg',
        'pexels',
        'stripe',
        'twilio',
        '@aws-sdk/client-bedrock-runtime',
        '@aws-sdk/lib-dynamodb',
        'playwright',
        'bullmq',
        'kafkajs',
        'amqplib',
        '@aws-sdk/client-sqs',
        'bun:sqlite',
        'bun:ffi',
        '@opentelemetry/api',
    ],
});
