/**
 * Code Review Pipeline — bare() + compose() + pipe()
 *
 * Real-world problem: Your team wants automated first-pass code review on every PR.
 * You need three specialized agents chained together:
 *
 *   1. DiffAnalyser  — parse the diff, identify changed files, classify risk level
 *   2. SecurityReviewer — scan for vulnerabilities, secrets, injection risks
 *   3. ReportWriter  — synthesize findings into a GitHub review comment (markdown)
 *
 * This example shows three composition styles:
 *   A. compose(a, b, c) — simple sequential pipeline
 *   B. pipe(a).then(b).then(c).run(prompt) — stepwise builder
 *   C. compose with transform + when options — conditional hand-off
 *
 * What it demonstrates:
 *   ✓  bare()   — zero-defaults agent with explicit LLM and custom hooks
 *   ✓  compose() — two-agent pipeline with optional transform
 *   ✓  pipe()   — chainable multi-agent builder
 *   ✓  Lifecycle hooks: beforeRun, afterRun, buildSystemPrompt
 *   ✓  MockLLMProvider — deterministic output, no API key needed
 *   ✓  Pattern to swap in real LLM for production
 *
 * Run: bun examples/code-review-pipeline.ts
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from 'dotenv';

config({
    path: path.join(path.dirname(fileURLToPath(import.meta.url)), '.env'),
    quiet: true,
});

import { bare, compose, pipe } from 'personaforge';
import { MockLLMProvider } from 'personaforge/test-utils';

// ── Mock LLMs (deterministic canned responses) ────────────────────────────

/**
 * In production, replace with:
 *   import { OpenAIProvider } from 'personaforge';
 *   const llm = new OpenAIProvider({ apiKey: process.env.OPENAI_API_KEY!, model: 'gpt-4o' });
 */
const diffLlm = new MockLLMProvider({
    response: [
        '## Diff Analysis',
        '',
        '**Changed files:** 3',
        '- `src/auth/login.ts` (+42 / -8 lines) — CRITICAL path',
        '- `src/db/queries.ts` (+15 / -0 lines) — DB access layer',
        '- `tests/auth.test.ts` (+30 / -5 lines) — Test coverage',
        '',
        '**Risk level:** HIGH',
        '**Summary:** Authentication flow modified; new DB queries added without parameterization check.',
        '**Recommend:** Full security review before merge.',
    ].join('\n'),
});

const securityLlm = new MockLLMProvider({
    response: [
        '## Security Review',
        '',
        '### Critical',
        '- **SQL Injection Risk** `src/db/queries.ts:23` — raw string interpolation in query builder.',
        '  ```ts',
        '  // BEFORE (vulnerable)',
        '  db.query(`SELECT * FROM users WHERE email = \'${email}\'`)',
        '  // FIX',
        '  db.query("SELECT * FROM users WHERE email = $1", [email])',
        '  ```',
        '',
        '### Warning',
        '- **Missing rate-limit** on `/auth/login` — brute-force attack vector.',
        '- **No CSRF token** checked in `login()` handler.',
        '',
        '### Pass',
        '- Passwords are bcrypt-hashed ✓',
        '- JWT expiry is set ✓',
        '- No API keys or secrets detected in diff ✓',
    ].join('\n'),
});

const reportLlm = new MockLLMProvider({
    response: [
        '## 🤖 Automated Code Review',
        '',
        '> **Verdict: REQUEST CHANGES** — 1 critical issue must be resolved before merge.',
        '',
        '### Critical (must fix)',
        '| File | Line | Issue |',
        '|------|------|-------|',
        '| `src/db/queries.ts` | 23 | SQL injection via string interpolation |',
        '',
        '### Warnings (should fix)',
        '| File | Issue |',
        '|------|-------|',
        '| `src/auth/login.ts` | No rate-limit on login endpoint |',
        '| `src/auth/login.ts` | Missing CSRF token validation |',
        '',
        '### Passed ✅',
        '- Passwords bcrypt-hashed',
        '- JWT expiry configured',
        '- No secrets in diff',
        '',
        '---',
        '*Generated by personaforge code-review pipeline · [docs](https://personaforge.dev)*',
    ].join('\n'),
});

// ── Sample PR diff ─────────────────────────────────────────────────────────

const PR_DIFF = `
diff --git a/src/auth/login.ts b/src/auth/login.ts
@@ -10,6 +10,42 @@
+export async function loginUser(email: string, password: string) {
+  const user = await db.query(\`SELECT * FROM users WHERE email = '\${email}'\`);
+  if (!user) throw new Error('User not found');
+  const valid = await bcrypt.compare(password, user.password_hash);
+  if (!valid) throw new Error('Invalid credentials');
+  return jwt.sign({ sub: user.id, email }, JWT_SECRET, { expiresIn: '7d' });
+}

diff --git a/src/db/queries.ts b/src/db/queries.ts
+export const findUserByEmail = (email: string) =>
+  db.query(\`SELECT * FROM users WHERE email = '\${email}'\`);
`.trim();

// ── Helpers ───────────────────────────────────────────────────────────────

function divider(title: string) {
    console.log(`\n${'='.repeat(12)} ${title} ${'='.repeat(12)}\n`);
}

// ── Approach A: compose() — simple sequential pipeline ────────────────────

async function approachA() {
    divider('Approach A: compose()');

    const diffAnalyser = bare({
        name: 'DiffAnalyser',
        instructions: 'Analyse a git diff. Identify changed files, risk level, and a one-paragraph summary.',
        llm: diffLlm,
        hooks: {
            afterRun: (result) => {
                console.log('[DiffAnalyser] completed — risk level extracted');
                return result;
            },
        },
    });

    const reportWriter = bare({
        name: 'ReportWriter',
        instructions: 'You receive a security analysis. Write a structured GitHub PR review comment in Markdown.',
        llm: reportLlm,
    });

    // SecurityReviewer between them
    const securityReviewer = bare({
        name: 'SecurityReviewer',
        instructions: 'You receive a diff analysis. Scan for security issues: SQL injection, secrets, auth flaws.',
        llm: securityLlm,
    });

    // compose(a, b, c) — chains three agents sequentially
    const pipeline = compose(diffAnalyser, securityReviewer, reportWriter);

    const result = await pipeline.run(
        `Please review this PR diff:\n\n${PR_DIFF}`,
        { onChunk: (text) => process.stdout.write(text) },
    );

    console.log('\n\n--- Final report ---\n');
    console.log(result.text);
    console.log(`\nSteps: ${result.steps}, Finish: ${result.finishReason}`);
}

// ── Approach B: pipe() — stepwise builder ─────────────────────────────────

async function approachB() {
    divider('Approach B: pipe().then().then().run()');

    const step1 = bare({ name: 'DiffAnalyser', instructions: 'Analyse the diff.', llm: diffLlm });
    const step2 = bare({ name: 'SecurityReviewer', instructions: 'Review security.', llm: securityLlm });
    const step3 = bare({ name: 'ReportWriter', instructions: 'Write the review comment.', llm: reportLlm });

    const result = await pipe(step1)
        .then(step2)
        .then(step3)
        .run(`Review this diff:\n\n${PR_DIFF}`);

    console.log('Pipeline result (last step):\n');
    console.log(result.text);
}

// ── Approach C: compose with when + transform ─────────────────────────────

async function approachC() {
    divider('Approach C: compose() with conditional hand-off');

    const highRiskLlm = new MockLLMProvider({
        response: '## Diff Analysis\n**Risk level:** HIGH\nSQL injection detected. Sending to security review.',
    });
    const lowRiskLlm = new MockLLMProvider({
        response: '## Diff Analysis\n**Risk level:** LOW\nNo critical changes. Minor style issues only.',
    });

    // Only escalate to SecurityReviewer when risk is HIGH
    const diffHighRisk = bare({ name: 'DiffAnalyser', instructions: 'Analyse the diff.', llm: highRiskLlm });
    const diffLowRisk  = bare({ name: 'DiffAnalyser', instructions: 'Analyse the diff.', llm: lowRiskLlm });
    const secReviewer  = bare({ name: 'SecurityReviewer', instructions: 'Security review.', llm: securityLlm });

    console.log('--- High-risk diff (escalates to security reviewer) ---\n');
    const highRiskPipeline = compose(diffHighRisk, secReviewer, {
        when: (result) => result.text.includes('HIGH'),
        transform: (result) => `Security review requested.\n\nContext:\n${result.text}`,
    });
    const r1 = await highRiskPipeline.run(`Review this diff:\n\n${PR_DIFF}`);
    console.log(r1.text);

    console.log('\n--- Low-risk diff (stops after diff analysis) ---\n');
    const lowRiskPipeline = compose(diffLowRisk, secReviewer, {
        when: (result) => result.text.includes('HIGH'),
    });
    const r2 = await lowRiskPipeline.run('Review this tiny whitespace-only diff.');
    console.log(r2.text);
    console.log('(Security reviewer skipped — risk was LOW)');
}

// ── Main ──────────────────────────────────────────────────────────────────

async function main() {
    console.log('personaforge — Code Review Pipeline: bare() + compose() + pipe()\n');
    console.log('PR diff:\n' + PR_DIFF + '\n');

    await approachA();
    await approachB();
    await approachC();

    divider('Done');
    console.log(`
Key patterns shown:
  bare(opts)               — zero-defaults agent; you control everything
  compose(a, b, c)         — sequential pipeline; output of each → input of next
  pipe(a).then(b).run(p)   — identical semantics; fluent step-by-step style
  compose(a, b, { when })  — conditional hand-off: only proceed when predicate is true
  compose(a, b, { transform }) — transform output before passing to next agent

Production tip: swap MockLLMProvider for OpenAIProvider or AnthropicProvider.
`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
